- name: Create a server instance
  os_server:
    cloud: ospcloud
    name: app1
    image: rhel-guest
    meta: "group=apps,deployment_name=QA"
    flavor: m2.small
    security_groups: apps
    key_name: ansible_ssh
    wait: yes
    nics:
    - net-name: ext_network
    userdata: |
        #!/bin/bash
        curl -o /tmp/openstack.pub http://www.opentlc.com/download/ansible_bootcamp/openstack_keys/openstack.pub
        cat /tmp/openstack.pub >> /home/cloud-user/.ssh/authorized_keys
        curl -o /tmp/internal.repo http://www.opentlc.com/download/ansible_bootcamp/repo/internal.repo
        cp /tmp/internal.repo /etc/yum.repos.d/internal.repo
  register: instanceip

- name: Add floating IP to app1
  os_floating_ip:
    cloud: ospcloud
    state: present
    reuse: yes
    server: app1
    network: ext_network
    wait: true
    timeout: 180
